# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b5a93e7ede33f0f2ddbbfd128253f5e36fd798b1191bbe01046bd164c0ac4d9ca862cc6ca923b8f6f023c8b68d2b016630dd4b2be85f3dbae60f1dc24d40737

test:
  secret_key_base: d6d3c63b4e6f37ce5863f854a32e9554e24ef20fc110a77abd738ffdd0e8eeb9f0dc02ebd4eebe2f9490583d935c92eaf1383fbfbed458afe6da100e051f0c32

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
